-- CREACION DE TABLA Y SECUENCIA PARA SOLICITUDES DE CAMBIO DE CONTRASENA
-- EJECUTAR CON UN USUARIO QUE TENGA PRIVILEGIOS PARA CREAR TABLAS, SECUENCIAS E INDICES

CREATE SEQUENCE SEQ_PASSWORD_CHANGE_REQUESTS
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    CACHE 20;

CREATE TABLE PASSWORD_CHANGE_REQUESTS (
    ID                NUMBER(19, 0)      NOT NULL,
    USUARIO_ID        NUMBER(19, 0)      NOT NULL,
    USERNAME_SNAPSHOT VARCHAR2(50 CHAR)  NOT NULL,
    CONTACT_EMAIL     VARCHAR2(150 CHAR),
    MOTIVO            VARCHAR2(500 CHAR),
    STATUS            VARCHAR2(20 CHAR)  NOT NULL,
    REQUESTED_AT      TIMESTAMP(6)       NOT NULL,
    PROCESSED_AT      TIMESTAMP(6),
    PROCESSED_BY      VARCHAR2(50 CHAR),
    ADMIN_NOTES       VARCHAR2(500 CHAR),
    UNLOCK_ACCOUNT    NUMBER(1, 0),
    CONSTRAINT PK_PASSWORD_CHANGE_REQUESTS PRIMARY KEY (ID)
);

ALTER TABLE PASSWORD_CHANGE_REQUESTS
    ADD CONSTRAINT FK_PASSWORD_CHANGE_REQUESTS_USUARIO
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIOS (ID);

CREATE INDEX IDX_PASSWORD_REQ_STATUS ON PASSWORD_CHANGE_REQUESTS (STATUS, REQUESTED_AT);
